-- AIMS (AI Innovation Manufacturing System) 데이터베이스 스키마
-- XAMPP의 phpMyAdmin 또는 mysql CLI로 이 파일을 실행해 DB를 생성하세요.

CREATE DATABASE IF NOT EXISTS aims CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aims;

CREATE TABLE IF NOT EXISTS agents (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  role_title VARCHAR(100) NOT NULL DEFAULT '',
  persona_intro VARCHAR(300) NOT NULL DEFAULT '',
  description VARCHAR(500) NOT NULL DEFAULT '',
  org_group VARCHAR(100) NOT NULL DEFAULT '',
  org_dept VARCHAR(100) NOT NULL DEFAULT '',
  org_team VARCHAR(100) NOT NULL DEFAULT '',
  uploader VARCHAR(100) NOT NULL DEFAULT '',
  file_path VARCHAR(255) NOT NULL,
  is_placeholder TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_agents_category (category),
  INDEX idx_agents_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_likes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  agent_id INT UNSIGNED NOT NULL,
  visitor_id VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_agent_visitor (agent_id, visitor_id),
  CONSTRAINT fk_agent_likes_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(100) NOT NULL DEFAULT '관리자',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notices_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(100) NOT NULL DEFAULT '익명',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_posts_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS feedback (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL DEFAULT '',
  title VARCHAR(300) NOT NULL,
  category VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visits (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  visitor_id VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_visits_visitor (visitor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
